#include <intravenous/runtime/iv_module_source_introspection_socket_rpc_notification_bridge.h>
#include <intravenous/runtime/iv_module_source_introspection_events.h>
#include <intravenous/runtime/socket_rpc_server.h>
namespace iv {
IV_DEFINE_BRIDGE(iv_module_source_introspection_socket_rpc_notification_bridge)
IV_SUBSCRIBE_LINKER_EVENT(iv_module_source_introspection_socket_rpc_notification_bridge, iv_runtime_iv_module_source_introspection_nodes_updated_event, &SocketRpcServer::handle_iv_module_source_introspection_nodes_updated)
} // namespace iv
