#!/usr/bin/env bash
set -euo pipefail

resolve_program() {
  local value="$1"
  if [[ -z "$value" ]]; then
    return 1
  fi

  if [[ "$value" = /* ]]; then
    printf '%s\n' "$value"
    return 0
  fi

  command -v "$value" 2>/dev/null || return 1
}

if [[ $# -gt 1 ]]; then
  echo "usage: $0 [intravenous-dir]" >&2
  exit 2
fi

intravenious_dir="${1:-${INTRAVENOUS_DIR:-}}"
if [[ -z "$intravenious_dir" ]]; then
  echo "INTRAVENOUS_DIR is not set and no directory argument was provided" >&2
  exit 1
fi

if [[ "$intravenious_dir" != /* ]]; then
  echo "INTRAVENOUS_DIR must be an absolute path: $intravenious_dir" >&2
  exit 1
fi

defaults_path="$intravenious_dir/.intravenious_defaults"

c_compiler="$(resolve_program "${CC:-}")" || c_compiler="$(resolve_program clang)" || c_compiler=""
cxx_compiler="$(resolve_program "${CXX:-}")" || cxx_compiler="$(resolve_program clang++)" || cxx_compiler=""
cmake_program="$(resolve_program cmake)" || cmake_program=""
make_program="$(resolve_program "${CMAKE_MAKE_PROGRAM:-}")" || make_program="$(resolve_program ninja)" || make_program=""
juce_dir="${JUCE_DIR:-}"

{
  echo "# Generated by scripts/generate_intravenious_defaults.sh"
  if [[ -n "$c_compiler" ]]; then
    echo "cCompiler=$c_compiler"
  fi
  if [[ -n "$cxx_compiler" ]]; then
    echo "cxxCompiler=$cxx_compiler"
  fi
  if [[ -n "$cmake_program" ]]; then
    echo "cmakeProgram=$cmake_program"
  fi
  if [[ -n "${CMAKE_GENERATOR:-}" ]]; then
    echo "cmakeGenerator=$CMAKE_GENERATOR"
  fi
  if [[ -n "$make_program" ]]; then
    echo "makeProgram=$make_program"
  fi
  if [[ -n "$juce_dir" ]]; then
    echo "juceDir=$juce_dir"
  fi
} > "$defaults_path"

echo "wrote $defaults_path"
