import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const watch = process.argv.includes("--watch");

const outdir = path.join(__dirname, "dist");
const mediaSource = path.join(__dirname, "media");
const mediaDest = path.join(outdir, "media");
const lanePluginsDir = path.join(__dirname, "src", "lanePlugins");

function copyMedia() {
    fs.mkdirSync(outdir, { recursive: true });
    if (fs.existsSync(mediaSource)) {
        fs.cpSync(mediaSource, mediaDest, { recursive: true });
    }
}

// Default-exporting modules in this directory are bundled automatically as
// lane presentations.  Adding a plugin therefore needs no lanes-host edit.
function discoverLanePlugins() {
    const files = fs.readdirSync(lanePluginsDir)
        .filter((file) => file.endsWith(".ts") && !["index.ts", "protocol.ts", "generated.ts"].includes(file))
        .sort();
    const imports = files.map((file, index) =>
        `import plugin${index} from "./${path.basename(file, ".ts")}";`).join("\n");
    const plugins = files.map((_, index) => `plugin${index}`).join(", ");
    fs.writeFileSync(
        path.join(lanePluginsDir, "generated.ts"),
        `// Generated by esbuild.mjs; do not edit.\n${imports}\n\nexport const discoveredLanePresentationPlugins = [${plugins}];\n`,
    );
}

const context = await esbuild.context({
    entryPoints: [path.join(__dirname, "src", "extension.ts")],
    outfile: path.join(outdir, "extension.js"),
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node22",
    sourcemap: true,
    tsconfig: path.join(__dirname, "tsconfig.json"),
    external: ["vscode"],
    loader: {
        ".svg": "file",
    },
    define: {
        "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV || "development"),
    },
});

copyMedia();
discoverLanePlugins();

if (watch) {
    await context.watch();
    console.log("Intravenous VS Code client esbuild watch started.");
} else {
    await context.rebuild();
    await context.dispose();
    console.log("Intravenous VS Code client build complete.");
}
