#pragma once

#include <filesystem>
#include <string>

namespace iv {
    inline bool is_package_tree_ignored_directory(std::filesystem::path const& path)
    {
        auto const name = path.filename();
        // These directories are generated by the build/editor toolchain. They
        // are neither package-discovery roots nor package dependency inputs.
        return name == "build" || name == ".git" || name == ".cache";
    }

    inline bool is_module_dependency_ignored_directory(std::filesystem::path const& path)
    {
        return is_package_tree_ignored_directory(path);
    }

    inline bool is_module_dependency_package_path(std::filesystem::path const& path)
    {
        auto const filename = path.filename();
        return filename != "iv_project.jsonl"
            && filename != "iv_project.jsonl.tmp"
            && filename != "compile_commands.json"
            && filename != "compile_commands.json.tmp";
    }

    struct ModuleDependency {
        std::string id;
        std::filesystem::path module_dir;
        std::filesystem::path entry_file;
        std::filesystem::file_time_type package_stamp {};
    };
}
